import * as THREE from 'three';
import { EffectComposer } from 'three/addons/postprocessing/EffectComposer.js';
import { RenderPass } from 'three/addons/postprocessing/RenderPass.js';
import { UnrealBloomPass } from 'three/addons/postprocessing/UnrealBloomPass.js';

const holder=document.getElementById('railScene'),canvas=document.getElementById('trainCanvas');
const scene=new THREE.Scene();scene.background=new THREE.Color(0x071521);scene.fog=new THREE.Fog(0x071521,18,55);
const camera=new THREE.PerspectiveCamera(48,1,.1,100);camera.position.set(10,7,15);camera.lookAt(0,0,-3);
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,innerWidth<800?1.25:1.8));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.shadowMap.enabled=true;
const composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));composer.addPass(new UnrealBloomPass(new THREE.Vector2(1,1),.8,.5,.5));

const steel=new THREE.MeshStandardMaterial({color:0x244859,metalness:.8,roughness:.25});const yellow=new THREE.MeshStandardMaterial({color:0xf5ba35,emissive:0x6d3c00,emissiveIntensity:.55,metalness:.55,roughness:.3});const dark=new THREE.MeshStandardMaterial({color:0x091018,metalness:.7,roughness:.22});const glass=new THREE.MeshPhysicalMaterial({color:0x8cd9ee,emissive:0x19485c,emissiveIntensity:.6,metalness:.2,roughness:.1,transparent:true,opacity:.78});
const train=new THREE.Group();scene.add(train);const engine=new THREE.Mesh(new THREE.BoxGeometry(3.2,1.5,6.2),steel);engine.position.y=1.55;engine.castShadow=true;train.add(engine);const nose=new THREE.Mesh(new THREE.CylinderGeometry(1.45,1.6,2.4,8),yellow);nose.rotation.x=Math.PI/2;nose.position.set(0,1.5,-4.2);train.add(nose);const cabin=new THREE.Mesh(new THREE.BoxGeometry(2.7,1.1,2.1),dark);cabin.position.set(0,2.75,-.8);train.add(cabin);const windshield=new THREE.Mesh(new THREE.BoxGeometry(2.25,.65,.06),glass);windshield.position.set(0,2.82,-1.88);train.add(windshield);const lightL=new THREE.PointLight(0xf5ba35,35,18);lightL.position.set(-.8,1.7,-5);train.add(lightL);const lightR=lightL.clone();lightR.position.x=.8;train.add(lightR);
for(const z of [-2.5,1.9])for(const x of [-1.35,1.35]){const wheel=new THREE.Mesh(new THREE.CylinderGeometry(.58,.58,.34,24),dark);wheel.rotation.z=Math.PI/2;wheel.position.set(x,.58,z);train.add(wheel);}
for(let carriage=0;carriage<2;carriage+=1){const car=new THREE.Mesh(new THREE.BoxGeometry(3,1.55,6.8),carriage?steel:yellow);car.position.set(0,1.55,4.5+carriage*7.2);car.castShadow=true;train.add(car);for(let windowIndex=0;windowIndex<4;windowIndex+=1){const win=new THREE.Mesh(new THREE.BoxGeometry(3.04,.55,.8),glass);win.position.set(0,1.85,2.3+carriage*7.2+windowIndex*1.25);train.add(win);}}
const ground=new THREE.Mesh(new THREE.PlaneGeometry(80,120),new THREE.MeshStandardMaterial({color:0x08131b,roughness:.88}));ground.rotation.x=-Math.PI/2;ground.position.y=0;ground.receiveShadow=true;scene.add(ground);for(const x of [-1.05,1.05]){const rail=new THREE.Mesh(new THREE.BoxGeometry(.12,.14,100),new THREE.MeshStandardMaterial({color:0x8b9aa0,metalness:.95,roughness:.18}));rail.position.set(x,.12,5);scene.add(rail);}for(let z=-45;z<55;z+=1.3){const sleeper=new THREE.Mesh(new THREE.BoxGeometry(4,.12,.28),dark);sleeper.position.set(0,.04,z);scene.add(sleeper);}
const poles=[];for(let z=-35;z<35;z+=9){for(const x of [-5,5]){const pole=new THREE.Mesh(new THREE.BoxGeometry(.12,5,.12),steel);pole.position.set(x,2.5,z);scene.add(pole);poles.push(pole);}}
scene.add(new THREE.HemisphereLight(0x9bdcff,0x071521,2));const sun=new THREE.DirectionalLight(0xffd788,3);sun.position.set(8,14,5);sun.castShadow=true;scene.add(sun);

let level=1,dragging=false;const speeds=[42,86,132],labels=['MANOBRA','CRUZEIRO','EXPRESSO'];document.getElementById('throttle').addEventListener('click',()=>{level=(level+1)%3;document.getElementById('throttleLabel').textContent=labels[level];document.getElementById('speedReadout').textContent=`${String(speeds[level]).padStart(3,'0')} KM/H`;document.querySelector('.rail-scene__throttle i').style.background=`linear-gradient(90deg,var(--yellow) ${(level+1)*33}%,rgba(255,255,255,.15) ${(level+1)*33}%)`;});holder.addEventListener('pointerdown',event=>{if(event.target.closest('button'))return;dragging=true;holder.setPointerCapture?.(event.pointerId)});holder.addEventListener('pointerup',()=>dragging=false);holder.addEventListener('pointermove',event=>{if(!dragging)return;camera.position.x=Math.max(-14,Math.min(14,camera.position.x+event.movementX*.035));camera.position.y=Math.max(3,Math.min(13,camera.position.y-event.movementY*.025));});
document.querySelectorAll('.station').forEach((station,index)=>station.addEventListener('click',()=>{document.querySelectorAll('.station').forEach(item=>item.classList.remove('is-active'));station.classList.add('is-active');document.getElementById('stationName').textContent=station.dataset.station;document.getElementById('stationEta').textContent=`ETA 0${index+2}:${String(18+index*11).padStart(2,'0')}`;}));
const resize=()=>{const width=holder.clientWidth,height=holder.clientHeight;renderer.setSize(width,height,false);composer.setSize(width,height);camera.aspect=width/height;camera.updateProjectionMatrix()};new ResizeObserver(resize).observe(holder);resize();const clock=new THREE.Clock();renderer.setAnimationLoop(()=>{const time=clock.getElapsedTime(),velocity=speeds[level]/86;train.position.z=((time*7*velocity+18)%28)-14;train.position.y=Math.sin(time*8*velocity)*.015;poles.forEach(pole=>{pole.position.z+=.17*velocity;if(pole.position.z>35)pole.position.z=-35});camera.lookAt(0,1.3,train.position.z-2);composer.render()});
