import * as THREE from 'three';
import { EffectComposer } from 'three/addons/postprocessing/EffectComposer.js';
import { RenderPass } from 'three/addons/postprocessing/RenderPass.js';
import { UnrealBloomPass } from 'three/addons/postprocessing/UnrealBloomPass.js';

const pad=value=>String(value).padStart(2,'0');
const atualizarRelogio=()=>{const agora=new Date();document.getElementById('relogio').textContent=`${pad(agora.getHours())}:${pad(agora.getMinutes())}:${pad(agora.getSeconds())}`;};atualizarRelogio();setInterval(atualizarRelogio,1000);
const wave=document.getElementById('wave');for(let index=0;index<96;index+=1){const line=document.createElement('i');line.style.setProperty('--h',`${15+Math.random()*85}%`);line.style.setProperty('--d',`${Math.random()*-.8}s`);wave.append(line);}
const publicButton=document.getElementById('modoPublico');publicButton.addEventListener('click',()=>{const pressed=publicButton.getAttribute('aria-pressed')==='true';publicButton.setAttribute('aria-pressed',String(!pressed));publicButton.querySelector('span').textContent=pressed?'MODO PÚBLICO DESATIVADO':'MODO PÚBLICO ATIVO';});
document.querySelectorAll('[data-command]').forEach(button=>button.addEventListener('click',()=>{document.getElementById('respostaComando').textContent=`${button.dataset.command}.`;button.closest('.commands').classList.add('has-response');}));

const holder=document.getElementById('reactor'),canvas=document.getElementById('jarvisScene'),trigger=document.getElementById('ativarJarvis');
const scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x050506,.06);const camera=new THREE.PerspectiveCamera(46,1,.1,60);camera.position.z=8.2;
const renderer=new THREE.WebGLRenderer({canvas,alpha:true,antialias:true,premultipliedAlpha:false,powerPreference:'high-performance'});renderer.setClearColor(0x050506,0);renderer.setPixelRatio(Math.min(devicePixelRatio,innerWidth<800?1.3:2));renderer.outputColorSpace=THREE.SRGBColorSpace;
const composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));const bloom=new UnrealBloomPass(new THREE.Vector2(1,1),1.8,.55,.08);composer.addPass(bloom);
const red=new THREE.MeshStandardMaterial({color:0xff3027,emissive:0xa40803,emissiveIntensity:3,metalness:.8,roughness:.16});const gold=new THREE.MeshStandardMaterial({color:0xffc857,emissive:0x7a3c00,emissiveIntensity:2.2,metalness:.75,roughness:.2});
const assembly=new THREE.Group();scene.add(assembly);const core=new THREE.Mesh(new THREE.IcosahedronGeometry(1.12,5),red);assembly.add(core);const cage=new THREE.Mesh(new THREE.DodecahedronGeometry(1.72,1),new THREE.MeshBasicMaterial({color:0xff5b52,wireframe:true,transparent:true,opacity:.35}));assembly.add(cage);
const rings=[];for(let index=0;index<12;index+=1){const ring=new THREE.Mesh(new THREE.TorusGeometry(1.95+index*.075,.012+(index%4===0?.025:0),10,100,Math.PI*(.45+Math.random())),index%4===0?gold:red);ring.rotation.set(Math.random()*Math.PI,Math.random()*Math.PI,Math.random()*Math.PI);assembly.add(ring);rings.push(ring);}
const positions=new Float32Array(1500*3);for(let index=0;index<1500;index+=1){const radius=3+Math.random()*9,angle=Math.random()*Math.PI*2;positions[index*3]=Math.cos(angle)*radius;positions[index*3+1]=(Math.random()-.5)*9;positions[index*3+2]=Math.sin(angle)*radius;}
const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.BufferAttribute(positions,3));const particles=new THREE.Points(geometry,new THREE.PointsMaterial({color:0xff473d,size:.025,transparent:true,opacity:.62,blending:THREE.AdditiveBlending}));scene.add(particles);
scene.add(new THREE.AmbientLight(0x45100d,2));const lamp=new THREE.PointLight(0xff342b,80,20);lamp.position.set(3,3,5);scene.add(lamp);const rim=new THREE.PointLight(0xffc857,35,16);rim.position.set(-3,-2,2);scene.add(rim);
let listening=false,dragging=false;const pointer=new THREE.Vector2(),target=new THREE.Vector2();trigger.addEventListener('click',()=>{listening=!listening;trigger.classList.toggle('is-listening',listening);document.getElementById('estadoNucleo').textContent=listening?'ESCUTANDO...':'ATIVAR ESCUTA';bloom.strength=listening?3.6:1.8;});holder.addEventListener('pointerdown',event=>{if(event.target.closest('button'))return;dragging=true;holder.setPointerCapture?.(event.pointerId);});holder.addEventListener('pointerup',()=>dragging=false);holder.addEventListener('pointermove',event=>{const rect=holder.getBoundingClientRect();target.set((event.clientX-rect.left)/rect.width*2-1,-((event.clientY-rect.top)/rect.height*2-1));if(dragging){assembly.rotation.y+=event.movementX*.008;assembly.rotation.x+=event.movementY*.006;}});
const renderArea=document.querySelector('.core');const resize=()=>{const width=renderArea.clientWidth,height=renderArea.clientHeight;renderer.setSize(width,height,false);composer.setSize(width,height);camera.aspect=width/height;camera.updateProjectionMatrix();};new ResizeObserver(resize).observe(renderArea);resize();const clock=new THREE.Clock();const motion=!matchMedia('(prefers-reduced-motion: reduce)').matches;
renderer.setAnimationLoop(()=>{const time=clock.getElapsedTime();pointer.lerp(target,.05);camera.position.x+=(pointer.x*.5-camera.position.x)*.035;camera.position.y+=(pointer.y*.35-camera.position.y)*.035;camera.lookAt(0,0,0);if(motion&&!dragging){assembly.rotation.y+=listening?.009:.003;cage.rotation.x=-time*.12;cage.rotation.z=time*.08;particles.rotation.y=time*.012;}core.scale.setScalar(1+Math.sin(time*(listening?5:2))*(listening?.1:.035));rings.forEach((ring,index)=>ring.rotation.z+=(index%2?-.003:.002));composer.render();});
