const radar = document.querySelector('.radar');
radar.style.cursor = 'grab';
let dragging = false;
let rotationX = 0;
let rotationY = 0;
let lastX = 0;
let lastY = 0;
radar.addEventListener('pointerdown', (event) => { dragging = true; lastX = event.clientX; lastY = event.clientY; radar.style.cursor = 'grabbing'; radar.setPointerCapture(event.pointerId); radar.classList.add('is-dragging'); });
radar.addEventListener('pointermove', (event) => {
  if (!dragging) return;
  rotationY += (event.clientX - lastX) * .35;
  rotationX -= (event.clientY - lastY) * .35;
  rotationX = Math.max(-28, Math.min(28, rotationX));
  lastX = event.clientX;
  lastY = event.clientY;
  radar.style.transform = `perspective(800px) rotateX(${rotationX}deg) rotateY(${rotationY}deg)`;
});
const stopDrag = (event) => { dragging = false; radar.style.cursor = 'grab'; radar.releasePointerCapture?.(event.pointerId); radar.classList.remove('is-dragging'); };
radar.addEventListener('pointerup', stopDrag);
radar.addEventListener('pointercancel', stopDrag);
document.querySelectorAll('[data-filter]').forEach((button) => button.addEventListener('click', () => { document.querySelectorAll('[data-filter]').forEach((item) => item.classList.remove('is-active')); button.classList.add('is-active'); document.querySelectorAll('.product').forEach((card) => { card.hidden = button.dataset.filter !== 'all' && card.dataset.filter !== card.dataset.state; }); }));
const toast = document.getElementById('priceToast');
document.querySelectorAll('.product-action').forEach((button) => button.addEventListener('click', () => { toast.textContent = `${button.dataset.target}: histórico de 30 dias carregado. Última leitura há 4 min.`; toast.classList.add('is-visible'); setTimeout(() => toast.classList.remove('is-visible'), 3200); }));
