const projetos = {
  ferroviaria: { codigo: 'PROJECT / 001', nome: 'Ferroviária LLGR', tipo: 'OPERATIONS SYSTEM', resumo: 'Uma central operacional para transformar rotas, sensores e manutenção em decisões claras.', descricao: 'Sistema web criado para digitalizar a gestão ferroviária. Operadores acompanham trens, rotas, estações, sensores, manutenções e itinerários em um mesmo fluxo.', stack: ['PHP', 'MySQL', 'Docker'], capacidades: ['Gestão de trens e rotas', 'Sensores e manutenções', 'Itinerários operacionais'], direcao: 'Interface de comando: densa onde precisa ser precisa, simples onde precisa ser rápida.', execucao: 'Suba os serviços com Docker e acesse o painel local.', comando: 'docker compose up', guia: 'setup-ferroviaria.html', github: 'https://github.com/lucaspwalter/ferroviaria-llgr', tema: 'rail', status: 'CONCLUÍDO' },
  turnover: { codigo: 'PROJECT / 002', nome: 'Turnover Dashboard', tipo: 'PEOPLE ANALYTICS', resumo: 'Risco de turnover convertido em sinais acionáveis para equipes de pessoas.', descricao: 'Dashboard que calcula um score auditável com seis fatores, organiza funcionários por risco e revela padrões por departamento.', stack: ['Python', 'FastAPI', 'React', 'PostgreSQL'], capacidades: ['Score com 6 fatores', 'Ranking por risco', 'Insights por departamento'], direcao: 'Dados não devem assustar: devem orientar a próxima decisão.', execucao: 'Prepare o ambiente Python, suba a API e inicie a interface.', comando: 'docker compose up', guia: 'setup-turnover.html', github: 'https://github.com/lucaspwalter/turnover-dashboard', tema: 'signal', status: 'CONCLUÍDO' },
  pricewatch: { codigo: 'PROJECT / 003', nome: 'PriceWatch', tipo: 'AUTOMATION ENGINE', resumo: 'Um radar de preços que trabalha em silêncio e avisa na hora certa.', descricao: 'Monitor de preços com job agendado, preço-alvo e notificação automática via WhatsApp quando a oportunidade aparece.', stack: ['Java', 'Spring Boot', 'Next.js', 'PostgreSQL'], capacidades: ['Monitoramento periódico', 'Alertas via WhatsApp', 'Preço-alvo por produto'], direcao: 'A interface mostra a oportunidade; a automação cuida do resto.', execucao: 'Suba banco, API e frontend conforme o guia do projeto.', comando: 'docker compose up -d', guia: 'setup-pricewatch.html', github: 'https://github.com/lucaspwalter/pricewatch', tema: 'amber', status: 'CONCLUÍDO' },
  barbershop: { codigo: 'PROJECT / 004', nome: 'Barbershop Scheduler', tipo: 'BOOKING PLATFORM', resumo: 'Agendamento sem conflito para barbearias que não podem perder tempo.', descricao: 'Plataforma com agenda, fila de espera, notificações e relatórios para transformar operação manual em experiência previsível.', stack: ['TypeScript', 'Fastify', 'Next.js', 'PostgreSQL'], capacidades: ['Conflito de horários', 'Fila de espera', 'Relatórios de desempenho'], direcao: 'Ritmo visual rápido, com informação importante sempre a um toque.', execucao: 'Instale dependências e inicie API e aplicação web.', comando: 'npm install && npm run dev', guia: 'setup-barbershop.html', github: 'https://github.com/lucaspwalter/barbershop-scheduler', tema: 'coral', status: 'CONCLUÍDO' },
  scraper: { codigo: 'PROJECT / 005', nome: 'Job Scraper', tipo: 'INTELLIGENCE PIPELINE', resumo: 'Uma estação pessoal para encontrar, classificar e acompanhar oportunidades.', descricao: 'Pipeline com FastAPI, React e workflows que pesquisa vagas, filtra tecnologia e administrativo e organiza o próximo passo da candidatura.', stack: ['Python', 'FastAPI', 'React', 'SQLite'], capacidades: ['Busca e classificação', 'Filtros por escopo', 'Acompanhamento de vagas'], direcao: 'Interface de terminal para um fluxo que precisa ser pessoal e rastreável.', execucao: 'Suba a API e a interface pelo roteiro do projeto.', comando: 'docker compose up', guia: 'setup-job-scraper.html', github: 'https://github.com/lucaspwalter/job-scraper', tema: 'terminal', status: 'CONCLUÍDO' },
  support: { codigo: 'PROJECT / 006', nome: 'Support System', tipo: 'REALTIME SERVICE', resumo: 'Atendimento ao vivo com fila, contexto e histórico no mesmo lugar.', descricao: 'Sistema de suporte com sessões em tempo real via WebSocket STOMP, fila de espera, painel de atendentes e histórico persistido.', stack: ['Java', 'Spring Boot', 'WebSocket', 'Next.js'], capacidades: ['Chat em tempo real', 'Fila de atendimento', 'Histórico persistido'], direcao: 'A conversa é o centro; o sistema desaparece enquanto mantém o contexto.', execucao: 'Inicie banco, backend e frontend conforme o guia.', comando: 'docker compose up', guia: 'setup-support-system.html', github: 'https://github.com/lucaspwalter/support-system', tema: 'cyan', status: 'CONCLUÍDO' },
  jarvis: { codigo: 'PROJECT / 007', nome: 'JARVIS', tipo: 'LOCAL INTELLIGENCE', resumo: 'Uma camada de inteligência local para ouvir, interpretar e agir com controle.', descricao: 'Assistente de voz local para Linux com wake word, Whisper, interpretação opcional via Ollama, síntese Piper e execução controlada de comandos registrados.', stack: ['Python', 'Whisper', 'Ollama', 'Piper'], capacidades: ['Wake word local', 'Transcrição em português', 'Comandos registrados'], direcao: 'Interface de sala de comando: escura, precisa e viva, como um sistema que está sempre escutando.', execucao: 'Instale dependências de áudio, configure o modelo local e inicie o serviço.', comando: 'python -m jarvis', guia: '#', github: 'https://github.com/lucaspwalter/jarvis', tema: 'jarvis', status: 'EM DESENVOLVIMENTO' },
  brasilium: { codigo: 'PROJECT / 008', nome: 'Brasilium Browser', tipo: 'PERSONAL BROWSER', resumo: 'Um navegador pessoal com identidade própria e foco em eficiência.', descricao: 'Build baseado em Chromium com branding Brasilium e ajustes de execução para reduzir consumo sem remover recursos essenciais.', stack: ['C++', 'Chromium', 'Linux', 'AppImage'], capacidades: ['Identidade Brasilium', 'Perfil pessoal persistente', 'Execução otimizada'], direcao: 'Menos ruído, mais controle: um navegador moldado para uso diário.', execucao: 'Baixe o AppImage, conceda permissão e execute.', comando: 'chmod +x Brasilium.AppImage && ./Brasilium.AppImage', guia: '#', github: 'https://github.com/lucaspwalter/helium-performance', tema: 'brasil', status: 'EM DESENVOLVIMENTO' }
};

const slug = new URLSearchParams(location.search).get('projeto') || 'jarvis';
const projeto = projetos[slug] || projetos.jarvis;
const setText = (id, value) => { document.getElementById(id).textContent = value; };
document.title = `${projeto.nome} — Projeto`;
document.body.dataset.tema = projeto.tema;
setText('projetoCodigo', projeto.codigo); setText('projetoNome', projeto.nome); setText('projetoTipo', projeto.tipo);
setText('projetoResumo', projeto.resumo); setText('projetoDescricao', projeto.descricao); setText('projetoDirecao', projeto.direcao);
setText('projetoExecucao', projeto.execucao); setText('projetoComando', projeto.comando); setText('consoleStatus', projeto.status);
setText('metricStack', projeto.stack[0]); setText('metricStatus', projeto.status); setText('consolePrompt', `> boot --${slug}`);
document.getElementById('projetoGithub').href = projeto.github;
document.getElementById('projetoGuia').href = projeto.guia;
document.getElementById('projetoStack').replaceChildren(...projeto.stack.map(item => Object.assign(document.createElement('span'), { textContent: item })));
document.getElementById('projetoCapacidades').replaceChildren(...projeto.capacidades.map(item => Object.assign(document.createElement('li'), { textContent: item })));

if (window.gsap) {
  gsap.from('.hero-copy > *, .hero-console', { opacity: 0, y: 28, duration: .9, stagger: .08, ease: 'power3.out' });
  gsap.to('.hero-grid', { backgroundPosition: '48px 48px', duration: 10, repeat: -1, ease: 'none' });
}
